parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: ferreteria
    database_user: root
    database_password: '123456'
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    title: La casa del Tornillo
    database_path: null

    userpass: smdi4dsi7
    adminpass: dym.es!dht
