DNT\WorkshopBundle\Entity\ArticuloProveedor:
  type: entity
  table: articuloProveedor
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    creado:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    modificado:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
  oneToMany:
    pedido:
      targetEntity: Pedido
      mappedBy: articuloProveedors
      cascade: [ "remove" ]
    devolucion:
      targetEntity: Devolucion
      mappedBy: articuloProveedors
      cascade: [ "remove" ]
  manyToOne:
    proveedor:
      targetEntity: Proveedor
      inversedBy: articuloProveedors
      joinColumn:
        name: id_proveedor
        referencedColumnName: id
    articulo:
      targetEntity: Articulo
      inversedBy: articuloProveedors
      joinColumn:
        name: id_articulo
        referencedColumnName: id
  lifecycleCallbacks: {  }
