DNT\WorkshopBundle\Entity\Articulo:
  type: entity
  table: articulo
  gedmo:
    soft_deleteable:
      field_name: eliminado
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: id
      generator:
        strategy: IDENTITY
    nombre:
      type: string
      length: 250
      fixed: false
      nullable: false
    cantidad:
      type: integer
      unsigned: false
      nullable: false
    costo:
      type: decimal
      nullable: false
    precioVenta:
      type: decimal
      nullable: false
      column: precio_venta
    descripcion:
      type: text
      nullable: true
    codigoBarra:
      type: string
      length: 250
      fixed: false
      nullable: false
      column: codigo_barra
    codigoProveedor:
      type: string
      length: 250
      fixed: false
      nullable: false
      column: codigo_proveedor
    eliminado:
      type: datetime
      nullable: true
    creado:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    modificado:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
  oneToOne:
    imagen:
      targetEntity: Imagen
      cascade: [ "persist" ]
      joinColumn:
        name: imagen_id
        referencedColumnName: id
  oneToMany:
    ArticuloProveedors:
      targetEntity: ArticuloProveedor
      mappedBy: articulo
      cascade: [ "all" ]
  manyToOne:
    idCategoria:
      targetEntity: Categoria
      cascade: [ "persist" ]
      inversedBy: articulos
      joinColumn:
        name: id_categoria
        referencedColumnName: id
  lifecycleCallbacks: {  }
