DNT\WorkshopBundle\Entity\Cliente:
  type: entity
  table: cliente
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: id
      generator:
        strategy: IDENTITY
    nombre:
      type: string
      length: 250
      fixed: false
      nullable: false
    apellido:
      type: string
      length: 250
      fixed: false
      nullable: false
    direccion:
      type: string
      length: 250
      fixed: false
      nullable: true
    telefono:
      type: string
      length: 250
      fixed: false
      nullable: true
    eliminado:
      type: integer
      unsigned: false
      nullable: false
    creado:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    modificado:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
  lifecycleCallbacks: {  }
