DNT\WorkshopBundle\Entity\Devolucion:
  type: entity
  repositoryClass: DNT\WorkshopBundle\Repository\DevolucionRepository
  table: devolucion
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: id
      generator:
        strategy: IDENTITY
    cantidad:
      type: integer
      unsigned: false
      nullable: false
    creado:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    modificado:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
    eliminado:
      type: integer
      unsigned: false
      nullable: false
    devuelto:
      type: integer
      unsigned: false
      nullable: false
  manyToOne:
    ArticuloProveedor:
      targetEntity: ArticuloProveedor
      inversedBy: devolucion
      joinColumn:
        ArticuloProveedor:
          name: id_articulo_proveedor
          referencedColumnName: id
  lifecycleCallbacks: {  }
