DNT\WorkshopBundle\Entity\Factura:
  type: entity
  table: factura
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: id
      generator:
        strategy: IDENTITY
    nroFactura:
      type: string
      length: 250
      fixed: false
      nullable: false
      column: nro_factura
    creado:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    modificado:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
  oneToOne:
    idCliente:
      targetEntity: Cliente
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        id_cliente:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
