DNT\WorkshopBundle\Entity\Imagen:
    type: entity
    table: imagen
    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        preRemove: [ storeFilenameForRemove ]
        postRemove: [ preUpload ]
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: 255
        path:
            type: string
            length: 255
            nullable: true
        file:
            type: text
            nullable: true
#    lifecycleCallbacks: {  }
