DNT\WorkshopBundle\Entity\Pedido:
  type: entity
  table: pedido
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: id
      generator:
        strategy: IDENTITY
    fecha:
      type: datetime
      nullable: true
    devolucion:
      type: integer
      unsigned: false
      nullable: false
    creado:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    modificado:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
  oneToOne:
    idArticuloProveedor:
      targetEntity: ArticuloProveedor
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        idArticuloProveedor:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
