DNT\WorkshopBundle\Entity\Pedido:
  type: entity
  repositoryClass: DNT\WorkshopBundle\Repository\PedidoRepository
  table: pedido
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: id
      generator:
        strategy: IDENTITY
    fecha:
      type: datetime
      nullable: true
    cantidad:
      type: integer
      unsigned: false
      nullable: false
    creado:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    modificado:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
    eliminado:
      type: integer
      unsigned: false
      nullable: false
    confirmado:
      type: integer
      unsigned: false
      nullable: false
  manyToOne:
    ArticuloProveedor:
      targetEntity: ArticuloProveedor
      inversedBy: pedido
      joinColumn:
        ArticuloProveedor:
          name: ArticuloProveedor
          referencedColumnName: id_articulo_proveedor
  lifecycleCallbacks: {  }
