DNT\WorkshopBundle\Entity\Pedido:
  type: entity
  table: pedido
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: id
      generator:
        strategy: IDENTITY
    fecha:
      type: datetime
      nullable: true
    devuelto:
      type: integer
      unsigned: false
      nullable: false
    cantidad:
      type: integer
      unsigned: false
      nullable: false
    creado:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    modificado:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
  manyToOne:
    ArticuloProveedor:
      targetEntity: ArticuloProveedor
      inversedBy: pedido
      joinColumn:
        ArticuloProveedor:
          name: ArticuloProveedor
          referencedColumnName: id_articulo_proveedor
  lifecycleCallbacks: {  }
