DNT\WorkshopBundle\Entity\Renglon:
  type: entity
  table: renglon
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: id
      generator:
        strategy: IDENTITY
    cantidad:
      type: integer
      length: 45
      fixed: false
      nullable: false
    precioArticulo:
      type: float
      length: 45
      fixed: false
      nullable: false
      column: precio_articulo
    precioTotal:
      type: float
      length: 45
      fixed: false
      nullable: false
      column: precio_total
    creado:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    modificado:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
  manyToOne:
    Factura:
      targetEntity: Factura
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        Factura:
          referencedColumnName: id
      orphanRemoval: false
    Articulo:
      targetEntity: Articulo
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        Articulo:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
