
RiotSignupBundle_root:
    pattern:  /
    defaults: { _controller: DNTWorkshopBundle:SimpleSearch:root}
DNTWorkshopBundle_homepage:
    pattern:  /busqueda_simple
    defaults: { _controller: DNTWorkshopBundle:SimpleSearch:index }
DNTWorkshopBundle_advanced:
    pattern:  /busqueda_avanzada
    defaults: { _controller: DNTWorkshopBundle:AdvancedSearch:index }
DNTWorkshopBundle_buscarProveedor:
    pattern:  /busqueda_proveedor
    defaults: { _controller: DNTWorkshopBundle:ProveedorSearch:index }
DNTWorkshopBundle_shop:
    pattern:  /carrito
    defaults: { _controller: DNTWorkshopBundle:Shop:index }
DNTWorkshopBundle_submitbuy:
    pattern:  /confirmarcarrito
    defaults: { _controller: DNTWorkshopBundle:Shop:submitBuy }
DNTWorkshopBundle_orders:
    pattern:  /pedidos
    defaults: { _controller: DNTWorkshopBundle:Order:index }
DNTWorkshopBundle_sales:
    pattern:  /ventas
    defaults: { _controller: DNTWorkshopBundle:Shop:sales }
DNTWorkshopBundle_sale:
    pattern:  /{id}/{_format}/venta
    defaults: { _controller: DNTWorkshopBundle:Shop:sale, _format: html }
    requirements:
        _format:  html|pdf
DNTWorkshopBundle_order:
    pattern:  /{id}/{_format}/order
    defaults: { _controller: DNTWorkshopBundle:Shop:order, _format: html }
    requirements:
        _format:  html|pdf


### Ajax
DNTWorkshopBundle_ajax_buy:
    pattern:  /ajax/buy
    defaults: { _controller: DNTWorkshopBundle:Ajax:buyArticle }
DNTWorkshopBundle_ajax_cleanbuy:
    pattern:  /ajax/cleanbuy
    defaults: { _controller: DNTWorkshopBundle:Ajax:cleanBuy }
DNTWorkshopBundle_ajax_order:
    pattern:  /ajax/order
    defaults: { _controller: DNTWorkshopBundle:Ajax:orderArticle }
DNTWorkshopBundle_ajax_delorder:
    pattern:  /ajax/order/delete
    defaults: { _controller: DNTWorkshopBundle:Ajax:orderDelete }
DNTWorkshopBundle_ajax_confirmorder:
    pattern:  /ajax/order/confirm
    defaults: { _controller: DNTWorkshopBundle:Ajax:orderConfirm }
DNTWorkshopBundle_ajax_return:
    pattern:  /ajax/return
    defaults: { _controller: DNTWorkshopBundle:Ajax:returnArticle }
DNTWorkshopBundle_ajax_confirmreturn:
    pattern:  /ajax/return/confirm
    defaults: { _controller: DNTWorkshopBundle:Ajax:returnConfirm }
DNTWorkshopBundle_ajax_provincelist:
    pattern:  /ajax/provincelist
    defaults: { _controller: DNTWorkshopBundle:Ajax:provinceList }
DNTWorkshopBundle_ajax_citylist:
    pattern:  /ajax/citylist
    defaults: { _controller: DNTWorkshopBundle:Ajax:cityList }

### Login
login:
    pattern:  /login
    defaults: { _controller: DNTWorkshopBundle:Login:login }
login_check:
    pattern:  /login_check
logout:
    pattern:   /logout

### ABMs
DNTWorkshopBundle_client:
    resource: "@DNTWorkshopBundle/Resources/config/routing/cliente.yml"
    prefix:   /cliente
DNTWorkshopBundle_articulo:
    resource: "@DNTWorkshopBundle/Resources/config/routing/articulo.yml"
    prefix:   /articulo
DNTWorkshopBundle_categoria:
    resource: "@DNTWorkshopBundle/Resources/config/routing/categoria.yml"
    prefix:   /categoria
DNTWorkshopBundle_factura:
    resource: "@DNTWorkshopBundle/Resources/config/routing/factura.yml"
    prefix:   /factura
DNTWorkshopBundle_pedido:
    resource: "@DNTWorkshopBundle/Resources/config/routing/pedido.yml"
    prefix:   /pedido
DNTWorkshopBundle_proveedor:
    resource: "@DNTWorkshopBundle/Resources/config/routing/proveedor.yml"
    prefix:   /proveedor
DNTWorkshopBundle_regla:
    resource: "@DNTWorkshopBundle/Resources/config/routing/regla.yml"
    prefix:   /regla
DNTWorkshopBundle_renglon:
    resource: "@DNTWorkshopBundle/Resources/config/routing/renglon.yml"
    prefix:   /renglon
DNTWorkshopBundle_articuloproveedor:
    resource: "@DNTWorkshopBundle/Resources/config/routing/articuloproveedor.yml"
    prefix:   /articuloproveedor

## Mantenimiento
DNTWorkshopBundle_datos:
    resource: "@DNTWorkshopBundle/Resources/config/routing/datos.yml"
    prefix:   /datos
#DNTWorkshopBundle_usuarios:
#    resource: "@DNTWorkshopBundle/Resources/config/routing/usuarios.yml"
#    prefix:   /usuarios
#DNTWorkshopBundle_extras:
#    resource: "@DNTWorkshopBundle/Resources/config/routing/extras.yml"
#    prefix:   /extras


dnt_csv_import_upload:
    pattern:   /import/upload/{alias}
    defaults:  { _controller: DNTWorkshopBundle:Import:upload }
dnt_csv_import_mapping:
    pattern:   /import/mapping/{alias}
    defaults:  { _controller: DNTWorkshopBundle:Import:mapping }
dnt_csv_import_process:
    pattern:   /import/process/{alias}
    defaults:  { _controller: DNTWorkshopBundle:Import:process }

dnt_csv_export_export:
    pattern:   /export/{alias}
    defaults:  { _controller: DNTWorkshopBundle:Export:export }
