datos:
    pattern:  /
    defaults: { _controller: "DNTWorkshopBundle:Datos:index" }

datos_savedb:
    pattern:  /savedb
    defaults: { _controller: "DNTWorkshopBundle:Datos:savedb" }

datos_restoredb:
    pattern:  /{backupFile}/restoredb
    defaults: { _controller: "DNTWorkshopBundle:Datos:restoredb" }

datos_deletedb:
    pattern:  /{backupFile}/deletedb
    defaults: { _controller: "DNTWorkshopBundle:Datos:deletedb" }

